const TERMS: Array<[string, string]> = [
  ["扬子克拉通", "Yangtze Craton"],
  ["黄陵穹隆", "Huangling Dome"],
  ["庙湾变质超基性岩", "Miaowan metamorphosed ultramafic rocks"],
  ["超基性岩", "ultramafic rock"],
  ["变质超基性岩", "metamorphosed ultramafic rock"],
  ["橄榄岩", "peridotite"],
  ["辉石岩", "pyroxenite"],
  ["蛇纹岩", "serpentinite"],
  ["蛇纹石化", "serpentinization"],
  ["滑石", "talc"],
  ["铬铁矿", "chromite"],
  ["初始俯冲", "subduction initiation"],
  ["俯冲起始", "subduction initiation"],
  ["洋内俯冲", "intra-oceanic subduction"],
  ["Rodinia 超大陆聚合", "Rodinia supercontinent assembly"],
  ["Rodinia 超大陆", "Rodinia supercontinent"],
  ["锆石 U-Pb 定年", "zircon U-Pb dating"],
  ["Re-Os 同位素", "Re-Os isotope"],
  ["模式年龄", "model age"],
  ["等时线年龄", "isochron age"],
  ["前寒武纪", "Precambrian"],
  ["新元古代", "Neoproterozoic"],
  ["变质岩", "metamorphic rock"],
  ["沉积盆地", "sedimentary basin"],
  ["岩浆作用", "magmatism"],
  ["地球化学", "geochemistry"],
  ["壳幔相互作用", "crust-mantle interaction"],
  ["亏损地幔", "depleted mantle"],
  ["俯冲带", "subduction zone"],
  ["弧前", "forearc"],
  ["岛弧", "island arc"],
  ["SSZ 型", "supra-subduction zone (SSZ) type"],
];

export const TERM_GLOSSARY_TEXT = TERMS.map(([zh, en]) => `- ${zh}: ${en}`).join("\n");
